/*
 * Open Hospital (www.open-hospital.org)
 * Copyright © 2006-2026 Informatici Senza Frontiere (info@informaticisenzafrontiere.org)
 *
 * Open Hospital is a free and open source software for healthcare data management.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * https://www.gnu.org/licenses/gpl-3.0-standalone.html
 */
package org.isf.plugin.maven;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/**
 * Assembles the plugin distribution ZIP after the JAR has been built.
 *
 * <p>Binds to the {@code package} phase, after the JAR is produced by
 * {@code maven-jar-plugin}. The resulting ZIP contains exactly two entries:
 * <pre>
 * {artifactId}-{version}.zip
 * ├── {artifactId}-{version}.jar   ← the plugin JAR
 * └── manifest.json                ← generated by the generate-manifest goal
 * </pre>
 *
 * <h3>Usage — declare both goals in the package-plugin profile</h3>
 * <pre>{@code
 * <plugin>
 *   <groupId>org.isf</groupId>
 *   <artifactId>plugin-maven-plugin</artifactId>
 *   <version>1.0.0</version>
 *   <executions>
 *     <execution>
 *       <id>generate-manifest</id>
 *       <goals><goal>generate-manifest</goal></goals>
 *     </execution>
 *     <execution>
 *       <id>package-zip</id>
 *       <goals><goal>package-zip</goal></goals>
 *     </execution>
 *   </executions>
 * </plugin>
 * }</pre>
 *
 * The ZIP is written to {@code target/{artifactId}-{version}.zip}.
 * Skip with {@code -Doh.plugin.skipZip=true}.
 */
@Mojo(
    name         = "package-zip",
    defaultPhase = LifecyclePhase.PACKAGE,
    threadSafe   = true
)
public class PackageZipMojo extends AbstractMojo {

    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    @Parameter(
        defaultValue = "${project.build.directory}",
        readonly     = true,
        required     = true
    )
    private File buildDirectory;

    @Parameter(defaultValue = "manifest.json")
    private String manifestFileName;

    @Parameter(defaultValue = "false", property = "oh.plugin.skipZip")
    private boolean skip;

    // -------------------------------------------------------------------------

    @Override
    public void execute() throws MojoExecutionException, MojoFailureException {
        if (skip) {
            getLog().info("oh:package-zip skipped (oh.plugin.skipZip=true)");
            return;
        }

        String artifactId = project.getArtifactId();
        String version    = project.getVersion();
        String jarName    = artifactId + "-" + version + ".jar";
        String zipName    = artifactId + "-" + version + ".zip";

        Path jarPath      = buildDirectory.toPath().resolve(jarName);
        Path manifestPath = buildDirectory.toPath()
                                          .resolve("classes")
                                          .resolve(manifestFileName);
        Path zipPath      = buildDirectory.toPath().resolve(zipName);

        if (!Files.exists(jarPath)) {
            throw new MojoFailureException(
                "oh:package-zip — JAR not found: " + jarPath +
                ". The JAR must be built before this goal runs.");
        }
        if (!Files.exists(manifestPath)) {
            throw new MojoFailureException(
                "oh:package-zip — manifest.json not found at: " + manifestPath +
                ". Make sure the generate-manifest execution is declared " +
                "before package-zip in the <executions> block.");
        }

        try {
            assembleZip(zipPath, jarPath, jarName, manifestPath);
        } catch (IOException e) {
            throw new MojoExecutionException(
                "oh:package-zip — failed to write " + zipPath, e);
        }

        getLog().info("oh:package-zip — " + zipPath.getFileName() +
                      " (" + humanReadableSize(zipPath) + ")");
    }

    // -------------------------------------------------------------------------

    private void assembleZip(Path zipPath, Path jarPath, String jarName,
                              Path manifestPath) throws IOException {
        try (ZipOutputStream zos =
                new ZipOutputStream(new FileOutputStream(zipPath.toFile()))) {
            addEntry(zos, jarPath.toFile(),      jarName);
            addEntry(zos, manifestPath.toFile(), manifestFileName);
        }
    }

    private static void addEntry(ZipOutputStream zos, File file,
                                  String entryName) throws IOException {
        zos.putNextEntry(new ZipEntry(entryName));
        try (FileInputStream fis = new FileInputStream(file)) {
            fis.transferTo(zos);
        }
        zos.closeEntry();
    }

    private static String humanReadableSize(Path path) {
        try {
            long bytes = Files.size(path);
            if (bytes < 1024)      return bytes + " B";
            if (bytes < 1024*1024) return (bytes / 1024) + " KB";
            return (bytes / (1024 * 1024)) + " MB";
        } catch (IOException e) {
            return "?";
        }
    }
}
